// Centralized Config Keys
export const CONFIG_KEYS = {
  SUPABASE_URL: 'SUPABASE_URL',
  API_KEY: 'API_KEY',
  NODE_ENV: 'NODE_ENV',
  NEXT_PUBLIC_SUPABASE_URL: 'NEXT_PUBLIC_SUPABASE_URL',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  SUPABASE_SERVICE_ROLE_KEY: 'SUPABASE_SERVICE_ROLE_KEY',
  // ... agrega aquí más claves
}; 